public class ArrayList {
    public static void main(String[] args) {
        /*WORKING OF ARRAYLIST 
        EVEN IT SEEMS TO BE SIZE IS NOT FIXED IN ARRAYLIST , INTERNALY SIZE IS FIXED
        WHEN NEW ELEMENT IN ADDED IN ARRAYSLIST , A NEW ARRAYLIST IS CREATED WITH THE SIZE DOUBLE
        THE PREVIOUS ONE AND ELEMENT OF OLD ARRAYLIST IS COPIED TO THE NEW ARRAYLSIT */
        
        

          
    }
}
